"""Private report objects; keys are generated by the backend, never by clients."""
import os
from pathlib import Path
import re
import tempfile
from typing import Protocol


MAX_PDF_BYTES = 16 * 1024 * 1024
KEY = re.compile(r"reports/[0-9a-f]{32}\.pdf\Z")


class StorageError(Exception):
    """Safe boundary: never expose SDK errors, paths or credentials."""


class ReportStorage(Protocol):
    """Create-only private bytes, bounded reads, and safe StorageError failures."""
    def put(self, key: str, data: bytes) -> None: ...
    def read(self, key: str) -> bytes: ...


def validate_key(key):
    if not isinstance(key, str) or not KEY.fullmatch(key):
        raise StorageError("Invalid object identity")


class LocalReportStorage:
    """Atomic create-only objects in an operator-owned private directory.

    Root and parents must be trusted, outside public/static paths. Symlink entries
    are refused. Temporary files are private and cannot be served by Flask.
    """
    def __init__(self, root):
        self.root = Path(root).resolve()

    def _directory(self):
        self.root.mkdir(mode=0o700, parents=True, exist_ok=True)
        if self.root.stat().st_mode & 0o077:
            raise StorageError("Storage directory must be private")
        directory = self.root / "reports"
        directory.mkdir(mode=0o700, exist_ok=True)
        if directory.is_symlink() or directory.resolve().parent != self.root:
            raise StorageError("Invalid storage directory")
        return directory

    def read(self, key):
        validate_key(key)
        try:
            path = self._directory() / key.split("/")[1]
            fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
            with os.fdopen(fd, "rb") as stream:
                data = stream.read(MAX_PDF_BYTES + 1)
            if len(data) > MAX_PDF_BYTES:
                raise StorageError("Object exceeds limit")
            return data
        except (OSError, ValueError) as error:
            raise StorageError("Object unavailable") from error

    def put(self, key, data):
        validate_key(key)
        if not data or len(data) > MAX_PDF_BYTES:
            raise StorageError("Object exceeds limit")
        temporary = None
        try:
            directory = self._directory()
            fd, temporary = tempfile.mkstemp(prefix=".upload-", dir=directory)
            with os.fdopen(fd, "wb") as stream:
                stream.write(data)
                stream.flush()
                os.fsync(stream.fileno())
            try:
                os.link(temporary, directory / key.split("/")[1])
            except FileExistsError:
                if self.read(key) != data:
                    raise StorageError("Object conflict")
            # Persist directory metadata before reporting successful upload.
            directory_fd = os.open(directory, os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        except OSError as error:
            raise StorageError("Storage unavailable") from error
        finally:
            if temporary is not None:
                os.unlink(temporary)


class AzureReportStorage:
    """Existing private container only. No provisioning, public URL or SAS API."""
    def __init__(self, account_url, container, credential=None, client=None):
        from urllib.parse import urlsplit
        parsed = urlsplit(account_url)
        if (parsed.scheme != "https" or not parsed.hostname
                or not parsed.hostname.endswith(".blob.core.windows.net")
                or parsed.username or parsed.password or parsed.query or parsed.fragment
                or parsed.path not in ("", "/") or parsed.port not in (None, 443)):
            raise ValueError("An Azure HTTPS account endpoint is required")
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]{1,61}[a-z0-9]", container or ""):
            raise ValueError("A private report container is required")
        if client is None:
            from azure.identity import DefaultAzureCredential
            from azure.storage.blob import BlobServiceClient
            client = BlobServiceClient(account_url, credential=credential or DefaultAzureCredential(),
                                       logging_enable=False, connection_timeout=5, read_timeout=30,
                                       retry_total=2)
        self.container = client.get_container_client(container)

    def _blob(self, key):
        validate_key(key)
        try:
            # Refuse configured public containers, including on read.
            if self.container.get_container_properties().get("public_access"):
                raise StorageError("Container must be private")
            return self.container.get_blob_client(key)
        except StorageError:
            raise
        except Exception as error:
            raise StorageError("Storage unavailable") from error

    def read(self, key):
        try:
            blob = self._blob(key)
            if blob.get_blob_properties().size > MAX_PDF_BYTES:
                raise StorageError("Object exceeds limit")
            data = blob.download_blob(offset=0, length=MAX_PDF_BYTES + 1, max_concurrency=1).readall()
            if len(data) > MAX_PDF_BYTES:
                raise StorageError("Object exceeds limit")
            return data
        except StorageError:
            raise
        except Exception as error:
            raise StorageError("Object unavailable") from error

    def put(self, key, data):
        from azure.core.exceptions import ResourceExistsError
        from azure.storage.blob import ContentSettings
        if not data or len(data) > MAX_PDF_BYTES:
            raise StorageError("Object exceeds limit")
        try:
            self._blob(key).upload_blob(data, overwrite=False, max_concurrency=1,
                content_settings=ContentSettings(content_type="application/pdf", cache_control="no-store"))
        except ResourceExistsError:
            if self.read(key) != data:
                raise StorageError("Object conflict")
        except StorageError:
            raise
        except Exception as error:
            raise StorageError("Storage unavailable") from error


def configure_report_storage(app):
    backend = app.config.get("REPORT_STORAGE_BACKEND", "local")
    if backend == "local":
        root = Path(app.config.get("REPORT_LOCAL_ROOT", "/workspace/ayursage-private-reports")).resolve()
        public = [Path(__file__).resolve().parents[2]]
        if any(root == path.resolve() or path.resolve() in root.parents for path in public):
            raise ValueError("Report storage must be outside application/public directories")
        storage = LocalReportStorage(root)
    elif backend == "azure":
        storage = AzureReportStorage(app.config.get("AZURE_REPORT_ACCOUNT_URL", ""),
                                     app.config.get("AZURE_REPORT_CONTAINER", ""))
    else:
        raise ValueError("Unsupported report storage backend")
    app.extensions["report_storage"] = storage
